### ISSUE TITLE
Type error while creating API class object

### ISSUE THREAD

**Issue by kumar550** [deep-compute/kwikapi.django#7]
![screen shot 2018-08-18 at 11 35 12 am](https://user-images.githubusercontent.com/18277890/44296349-ee563f00-a2da-11e8-924d-79e1f2f98e06.png)

@RamanjaneyuluIdavalapati 
- As per the documentation, while creating an **object for API class** we are sending **logger object** and the **default version name.**

**Comment by jaswanth098** [comment]
This fixed in readme and merged to master branch closing this
